apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-manager
spec:
  selector:
    matchLabels:
      app: stock-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-manager
    spec:
      containers:
        - name: stock-manager
          image: evestidor/stock-manager:master
